### ISSUE TITLE
HTML form example doesn't match description

### ISSUE THREAD

**Issue by jeffro94** [mdn/learning-area#112]
In the last example of [How to structure an HTML form](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form), the description describes an `<input>` element of type `date` for the CC expiration date. It mentions how this input type will _come up with a date picker widget in supporting browsers, and fall back to a normal text input in non-supporting browsers_.
  
But the code example has only a plain text input element. This is confusing.

I'm not sure if this is the correct place to report this; please let me know if so. Thanks

**Comment by chrisdavidmills** [comment]
Hi there, thanks for reporting this! I have fixed it now, making that one a type of `date`, and also making the number input into type `number`.
