### ISSUE TITLE
Need to fork the repository or not ?

### ISSUE THREAD

**Issue by fleuronvilik** [mdn/learning-area#120]
Hello!

Learning with MDN involves to download files like examples or starter code from the learning area's repository. Instead of doing this one by one, I wanted to clone the entire repository and just browse it locally. This is not for contributions purpose. Is it allowed and if so, do I need to fork the repo first ?

Thanks you.

**Comment by chrisdavidmills** [comment]
@fleuronvilik Yes, you can do this — no problem!

In case you need any help, we already wrote up how to get the examples here: https://developer.mozilla.org/en-US/docs/Learn#Getting_our_code_examples

**Comment by fleuronvilik** [comment]
@chrisdavidmills Thank you. Both for the answer and for the work on MDN.
