### ISSUE TITLE
Link Active learning where it's not clear enough

### ISSUE THREAD

**Issue by campos20** [mdn/learning-area#124]
On the previous sessions (HTML and CSS), Active Learning was followed by a clear interactive feature. In CSS, it's not that clear (see **just before** [this link](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Syntax#CSS_statements)).

It took me a while to figure that "the above example" or "in our example" was about the previous images. At first sight, I assumed it was a load error. This new approach both breaks the clear standard adopted so far and the interactivity.

A solution would be linking the image.

**Comment by chrisdavidmills** [comment]
I appreciate this is not very clear. To make it clearer, I've added CSS blocks in the actual active learning  sections and changed the wording. Let me know if you think this is better.

**Comment by campos20** [comment]
Awesome!
