### ISSUE TITLE
Maybe make a guide showing how to setup a local environment?

### ISSUE THREAD

**Issue by JonDevOps** [mdn/learning-area#143]

**Comment by JonDevOps** [comment]
Never mind, i did not realize it was only the example projects here and not the actual documentation..

**Comment by chrisdavidmills** [comment]
https://github.com/mdn/sprints/issues is the best place to post such suggestions.

Also FYI, I am currently writing a spec for some new docs that will cover frameworks and the modern tools ecosystem for beginners. I am intending to cover setting up a useful environnment with tests, build steps, etc.

**Comment by JonDevOps** [comment]
I found tools like http://zealdocs.org/ to be extremely useful for offline use but it still does not show how to contribute.
