### ISSUE TITLE
Small typo in Async javascript, "rate frame" to "framerate"

### ISSUE THREAD

**Issue by Mohammed-Shoaib** [mdn/learning-area#144]
Hey, I was going through the javascript tutorial and I found a small typo. :mag_right:

The typo can be found in [this page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Choosing_the_right_approach#requestAnimationFrame()) in the following directory:
* Asynchronous javascript
  * Choosing the right approach
    * requestAnimationFrame()

The typo is in the following line:
> You should, if at all possible, use this instead of setInterval()/recursive setTimeout(), unless you need a specific **rate frame**.

The word **rate frame** needs to be corrected to **framerate**. In all other places, framerate is used, this place alone needs to be corrected.

I'd be glad to do this change and I wanted to do a pull request on it, however, the explanation files cannot be found in this repo. It contains the code for the tutorials. :computer:

It is a small typo but I still thought of letting you know! :sweat_smile:

**Comment by chrisdavidmills** [comment]
Fixed! Thanks for reporting ;-)
