### ISSUE TITLE
Responsive Images on Google Chrome

### ISSUE THREAD

**Issue by LukeFang0706** [mdn/learning-area#148]
Hi there,

I'm new for html and studying [responsive.html](https://github.com/mdn/learning-area/blob/master/html/multimedia-and-embedding/responsive-images/responsive.html) this topic. 
On firefox, I can clearly see the results on Network Inspector that browser would download different-width jpg files when I set different viewport width. With the same source code, however, I can't see the same results on Google Chrome, even disable the cache.
Is there something I don't recognize or Do I misunderstand the content?

Thanks a lot!!

Luke

**Comment by 49-22** [comment]
Probably you could have selected a filter in the network panel.

**Comment by avivmu** [comment]
@chrisdavidmills Kindly close. @LukeFang0706 If this issue still bothers you let us know here
