### ISSUE TITLE
error with  YouTube video search example

### ISSUE THREAD

**Issue by plee61** [mdn/learning-area#160]
Hello,
I am not able to run the example for third-party API as posted https://github.com/mdn/learning-area/tree/master/javascript/apis/third-party-apis/youtube. 

The error i received from Chrome is 'Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null').' 

I did get a key from Google using the instructions on index.html. I have tried to debug, the error seems to come from gapi.client.load. Please help.

Cheers,
Hannah

**Comment by chrisdavidmills** [comment]
Hi @plee61 ,

The example won't work if you are just running it from the local file. You need to run the example through a local web server, or upload it to a service like GitHub pages:

* https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
* https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Using_Github_pages

**Comment by plee61** [comment]
Thank Chris. It works running on Github: 

https://plee61.github.io/learning-area/third-party-apis/youtube/

But errors as below upon submitting search

www-widgetapi.js:115 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://plee61.github.io').

**Comment by avivmu** [comment]
@chrisdavidmills close?
