### ISSUE TITLE
How to Autoplay both Loop Video/Audio in all the browsers?

### ISSUE THREAD

**Issue by castana1962** [mdn/learning-area#161]
Hi All
Since I am new in this topic and like I can’t automatically play a video with sound because Autoplay policy of modern browsers rulers, I was looking for some solution for this one.
I read that I can easily solve this issue by forcing a user interaction before you start to playback the video( for example adding a black background with a Click to play button) for it, Could you help me and give the code to do it in my own html file?
Thanks for your time
Best Regards
Alejandro Castan

**Comment by chrisdavidmills** [comment]
Hi there,

There is bound to be some code in here to help you:

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs

Basically, you need a video element:

```
<video src="myVideo.mp4">
```

And a button

```
<button>Play</button>
```

And some code to wire up the button to the video

```
let videoElem = document.querySelector('video');
let playBtn = document.querySelector('button');

playBtn.addEventListener('click', function() {
  videoElem.play();
})
```

If you want to make the button look nice, for example overlaying on top of the video, you'll need to use some CSS to style it, perhaps some absolute positioning to position it on the top?

Hope this helps.

**Comment by castana1962** [comment]
Hi chrisdavidmills
I will try it !!!
Thank you for your help !!!
Alejandro

**Comment by castana1962** [comment]
Hi chrisdavidmills,
Sorry again but I added what you told me and it is not working for me. I cannot the Play button in my background. Surely, I am making a mistake...Could you help me to fix it? Thanks for your time
My code is the following


> 
<!DOCTYPE HTML>

<html>
   <head>

     <title>VR Salud</title>
        <style>
   			html, body { margin: 0; padding:0; overflow: hidden; }
   			h1 { color:white; position:absolute; top:95%; z-index:100; width:100%; text-align: center;; transform: translate(0,-100%); font-family: 'Raleway', sans-serif; font-weight: 100; letter-spacing: 1px; text-transform: lowercase; font-size: 30px; }
   			#videoBacker {  background-size: cover; object-fit: cover; z-index: 9; opacity:.3; position: absolute; top:0px; left:0px; width:100vw; height: 100vh; transition: 1s opacity ease-in-out;
   }

   </style>


      <video width="1920" height="1080" controls autoplay loop>
          <source src="Hexxcaudio.webm" type="video/webm">
      <p>Your browser doesn't support HTML5 video. Here is a <a href="Hexxcaudio.webm">link to the video</a> instead.</p>
    </video>

    <button>Play</button>

  <script>
    let videoElem = document.querySelector('video');
   let playBtn = document.querySelector('button');

   playBtn.addEventListener('click', function() {
  videoElem.play();
});

  </script>


</html>

>

**Comment by chrisdavidmills** [comment]
This worked fine for me:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>VR Salud</title>
   <style>
   html, body { margin: 0; padding:0; overflow: hidden; }
   h1 { color:white; position:absolute; top:95%; z-index:100; width:100%; text-align: center;; transform: translate(0,-100%); font-family: 'Raleway', sans-serif; font-weight: 100; letter-spacing: 1px; text-transform: lowercase; font-size: 30px; }
</style>
  </head>
  <body>
    <video width="640" height="320" autoplay loop>
    <source src="rabbit320.mp4" type="video/mp4">
<p>Your browser doesn't support HTML5 video.</p>
</video>

<button>Play</button>

<script> let videoElem = document.querySelector('video'); let playBtn = document.querySelector('button'); playBtn.addEventListener('click', function() { videoElem.play(); }); </script>
  </body>
</html>
```

It was probably the video format — I don't think we support WebM any more, and you can play mp4 anywhere.

**Comment by castana1962** [comment]
Hi again
Great !!! 
It is working well if I add the 640 x 320 px ( I can see the Play button and see the video and audio)
I do not want to abuse of your generosity but since that my video is 1920 x 1080, px ( I cannot the Play button). for it, Do you know how I could add the Play button above the video and click the button to see it? Would it be possible? One more time, thanks for your help. Alejandro

**Comment by chrisdavidmills** [comment]
I think this is just because your video is too big and so is pushing the button offscreen?

You could get the button onscreen easily by just putting it before the video in the source order.

Or you could use absolute positioning to position it over the video, for example

```
button {
  position: absolute;
  top: 0;
  left: 0;
} 
```

by default, absolute position positions elements relative to the `<body>` element. If you want to have them positioned relative to a different element, you'll need to nest them inside that element, and make sure that element has positioning set on it (like `relative`), so that the positioning context becomes that element, and not the body element.

So for example:

```
<div class="container">
  <video width="640" height="320" autoplay loop>
    <source src="rabbit320.mp4" type="video/mp4">
  <p>Your browser doesn't support HTML5 video.</p>
  </video>
  <button>Play</button>
</div>
```

And some CSS:

```
.container {
  position: relative;
}

button {
  position: absolute;
  top: 0;
  left: 0;
}
```

The video would then site inside the container, and the button would be positioned relative to the container's edges, regardless of there the container ends up on the page.

**Comment by chrisdavidmills** [comment]
The correct properties to use are top, bottom, left, right.

The following tutorial should help:

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning

**Comment by castana1962** [comment]
Hello chrisdavidmills
I apologize for bothering you again but I have a problem with the Video in my website because it is not working like Responsive Design, for it, Could you help me with it? Tha;s for your time
The code is the following
Index.html
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="index.css" rel= "stylesheet" type="text/css">
        <title>VR Salud</title>
   <style>
   html, body { margin: 0; padding:0; overflow: hidden; }
   h1 { color:white; position:absolute; top:95%; z-index:100; width:100%; text-align: center;; transform: translate(0,-100%); font-family: 'Raleway', sans-serif; font-weight: 100; letter-spacing: 1px; text-transform: lowercase; font-size: 30px; }
</style>
  </head>
  <body>


    <video width="1920" height="1080" loop id="video_sample">
    <source src="VRHealthWeb.mp4" type="video/mp4">
<p>Your browser doesn't support HTML5 video.</p>
</video>

</div>
/*<button id = "btn" onclick = button_action();> Play Here </button>;


<script type="text/javascript">
var store_video = document.getElementById('video_sample');
var btn_store = document.getElementById('btn');
function button_action(){
if(store_video.paused){
  store_video.play();
  btn_store.innerHTML = "Paused Intro";
}
else {
  store_video.pause();
  btn_store.innerHTML = "Play Intro";
}
}

/*let videoElem = document.querySelector('video'); let playBtn = document.querySelector('button'); playBtn.addEventListener('click', function() { videoElem.play(); }); */</script>
  </body>
</html>
`
Index.css
`.container {
  position: relative;
}

button {
  position: absolute;
  top: 0;
  left: 0;
}
`

**Comment by castana1962** [comment]
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="index1.css" rel= "stylesheet" type="text/css">
        <title>VR Salud</title>
   <style>
   html, body { margin: 0; padding:0; overflow: hidden; }
   h1 { color:white; position:absolute; top:95%; z-index:100; width:100%; text-align: center;; transform: translate(0,-100%); font-family: 'Raleway', sans-serif; font-weight: 100; letter-spacing: 1px; text-transform: lowercase; font-size: 30px; }
</style>
  </head>
  <body>


    <video width="1920" height="1080" loop id="video_sample">
    <source src="VRHealthWeb.mp4" type="video/mp4">
<p>Your browser doesn't support HTML5 video.</p>
</video>

</div>
/*<button id = "btn" onclick = button_action();> Play Here </button>;


<script type="text/javascript">
var store_video = document.getElementById('video_sample');
var btn_store = document.getElementById('btn');
function button_action(){
if(store_video.paused){
  store_video.play();
  btn_store.innerHTML = "Paused Intro";
}
else {
  store_video.pause();
  btn_store.innerHTML = "Play Intro";
}
}

/*let videoElem = document.querySelector('video'); let playBtn = document.querySelector('button'); playBtn.addEventListener('click', function() { videoElem.play(); }); */</script>
  </body>
</html>`

**Comment by permanar** [comment]
@castana1962 Could you please be more informative about your issue? I mean like, providing some of your code (you probably need jsfiddle.net or pastebin.com if its too long), screenshot of your site, or maybe like your console log.

**Comment by chrisdavidmills** [comment]
@castana1962 I missed your last query completely - really sorry!

To learn about responsive design, start by reading https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design

You can get replaced elements like `<img>` and `<video>` to behave responsively pretty cheaply. Usually something like this will work:

```
img, video, iframe {
  display: block;
  max-width: 100%;
}
```

**Comment by avivmu** [comment]
@castana1962 / @chrisdavidmills it seems like this can be closed, if so kindly close
