### ISSUE TITLE
这个pattern.png图片打不开，同时也无法下载！

### ISSUE THREAD

**Issue by dingguangbo** [mdn/learning-area#165]
https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page

**Comment by KanzakiYui** [comment]
I can view the pics, could you double check if it's fixed now? 🤔

**Comment by chrisdavidmills** [comment]
What was the problem in the first place?

**Comment by williamBieneman** [comment]
> The image pattern.png will not open, and also will not download!

**Comment by Patogumi** [comment]
Mister Bieneman, hope you are doing fine. For currently opening you have to follow the link to the very end, I had the same problem. Hope you have solved it already.

**Comment by avivmu** [comment]
@chrisdavidmills let's close this
