### ISSUE TITLE
Error parsing metadata using learning-area's videos

### ISSUE THREAD

**Issue by Valsaa** [mdn/learning-area#180]
Hello everyone,

**Context :** 
-  Applying the guide [Video and audio content](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content#Media_file_support_in_browsers) from MDN web docs
- Example videos from this GitHub project: 
[rabbit320.mp4](https://github.com/mdn/learning-area/blob/master/html/multimedia-and-embedding/video-and-audio-content/rabbit320.mp4)
[rabbit320.webm](https://github.com/mdn/learning-area/blob/master/html/multimedia-and-embedding/video-and-audio-content/rabbit320.webm)
-  Browser version : Firefox 72.0.1 (64 bit)

**Issue :**
- When applying the guide, I get this error for both format (mp4 and webm) from the Firefox Console Inspector :
`Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006)
Details: static MP4Metadata::ResultAndByteBuffer __cdecl mozilla::MP4Metadata::Metadata(mozilla::ByteStream *): Cannot parse metadata`

**Workaround :**
- Get the videos from the [live example](https://mdn.github.io/learning-area/html/multimedia-and-embedding/video-and-audio-content/multiple-video-formats.html)

**Assumption :**
- The video files from this project are obsolete for Firefox 72.0.1 (64 bit)

**Possible resolution :**
- Update the videos from this project with those in the live example

Thanks in advance and have a nice day !
Valsaa

**Comment by chrisdavidmills** [comment]
This is a strange one. The files linked to in the project and the ones in the live example are **the same** video files. What does your code look like? Have you got a live example somewhere I can look at?

**Comment by Valsaa** [comment]
Hi chrisdavidmills,

From what you wrote, I managed to understand my mistake but as you requested, my code is the same from one of [yours](https://github.com/mdn/learning-area/blob/master/html/multimedia-and-embedding/video-and-audio-content/multiple-video-formats.html).

In fact, on [this GitHub page](https://github.com/mdn/learning-area/tree/master/html/multimedia-and-embedding/video-and-audio-content), I right-clicked on one of the videos and selected _Save Link As_.
![image](https://user-images.githubusercontent.com/16226087/72075898-e72b3900-32f4-11ea-97fb-066582e4cd40.png)

Apparently, this is not the right thing to do because doing so, I locally saved the HTML of the GitHub page hosting the video **with the name of the video** instead of the video itself .

On the same [page](https://github.com/mdn/learning-area/tree/master/html/multimedia-and-embedding/video-and-audio-content), I would rather click on the link of the video and from there, select the _Download_ button. 
![image](https://user-images.githubusercontent.com/16226087/72076368-b4357500-32f5-11ea-9145-0137aeae6379.png)

Next, with the video playing itself and I would right-click and select _Save Video As_ to get the correct video file.
![image](https://user-images.githubusercontent.com/16226087/72076433-cfa08000-32f5-11ea-95d6-427bd745924d.png)

This is a beginner Github mistake... but it taught me a lesson !
At least, thank you for your reactivity.

Valsaa
