### ISSUE TITLE
[minor issue] matches more pattern than said

### ISSUE THREAD

**Issue by rmNULL** [mdn/learning-area#185]
https://github.com/mdn/learning-area/blob/1466fc0d13ff2c3b37e454560ceedd913d4e73bc/html/forms/form-validation/fruit-pattern.html#L21

the given pattern also matches "|anana" or "|herry".
correction is "[bB]" in place of "[b|B]"

**Comment by chrisdavidmills** [comment]
Thanks for pinging me about this! I've fixed it in the repo, and the associated article:

https://wiki.developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation
