### ISSUE TITLE
Nytimes using var

### ISSUE THREAD

**Issue by garcai** [mdn/learning-area#192]
both nytimes/index.html and nytimes/nytimes_start.html are using var instead of const or let.
I have created a local branch with fixes and tested.
Also 2 vars submitBtn and playNav aren't used so I commented them out.
Can I push them to the repository?

**Comment by chrisdavidmills** [comment]
Hi @garcai ! Thanks for pointing this out; I am a bit annoyed at myself, as I took the time to update the code in the actual tutorial, but not on the GitHub version, i.e. [here](https://github.com/mdn/learning-area/blob/master/javascript/apis/third-party-apis/nytimes/index.html).

So please, if you've got a working version, I'd be happy to look at a PR.

**Comment by garcai** [comment]
I did reply to the email, but not sure that's the right way, so sorry about sending 2 PR, first had a bunch of useless commits. Thank You for all the work you put in this

**Comment by avivmu** [comment]
@garcai / @chrisdavidmills kindly close. As a side note, let's close inactive issues automatically unless otherwise needed. A quick google search came up with https://github.com/apps/stale which does exactly this.
