### ISSUE TITLE
Wrong use of <address> in making-up-a-letter-finished?

### ISSUE THREAD

**Issue by hutstep** [mdn/learning-area#2]
According to the marking guide one should wrap both addresses at the top each in an `<address>` element.
https://github.com/mdn/learning-area/blob/master/html/introduction-to-html/marking-up-a-letter-finished/marking-guide.md
Isn't that wrong? In MDN it states:
![mdn-address](https://cloud.githubusercontent.com/assets/18348355/19286279/5d73e22c-8ffd-11e6-8fb0-2bc7c4e90b1c.png)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address

According to this, wrapping the second address (Miss Eileen Dover) in an `<address>` element is definitely wrong.
I'm not sure about the first address (Dr. Eleanor Gaye), but I think it's okay, because it's the author of the letter.

**Comment by chrisdavidmills** [comment]
Only just seen this; my apologies. We've fixed this now.
