### ISSUE TITLE
Not a issue , but i need some help

### ISSUE THREAD

**Issue by AnilSonix** [mdn/learning-area#208]
when I right-click on the video and select **show controls**. Clicking on video plays it, but it doesn't remove class **hidden**.
Why is that?

**Comment by chrisdavidmills** [comment]
Hi @AnilSonix! Which example are you talking about? I'd imagine it involves an HTML5 video player with custom controls?

When you right-click on an HTML5 video and choose "show controls", that will only control the native video controls that the browser provides - it won't do anything to the custom controls that you might have created for it. Unfortunately this means that you could end up with the user showing the native controls at the same time as the custom controls, which looks pretty bad ;-)

Have a play with the example at the top of this section to see what I mean: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs#The_HTMLMediaElement_API

**Comment by AnilSonix** [comment]
Yes, I'm referring to native HTML5 video player.
And the example is [https://github.com/mdn/learning-area/blob/master/javascript/building-blocks/events/show-video-box.html](https://github.com/mdn/learning-area/blob/master/javascript/building-blocks/events/show-video-box.html )

Does **show controls** stop event propagation in the above example?
If controls are hidden, the example behaves as mentioned in MDN.

**Comment by chrisdavidmills** [comment]
@AnilSonix Ah, that example!

So this is really interesting — I had never even considered how the native controls could affect event propagation.

I think that the reason the events don't propagate through to the native controls is that they are not actually part of the visible DOM — they are part of a shadow DOM, which is not accessible via the DOM, or JavaScript, etc. So clicking on any part of the native controls doesn't hide the video.

**Comment by AnilSonix** [comment]
Thanks @chrisdavidmills for helping me out.

**Comment by chrisdavidmills** [comment]
You're welcome!
