### ISSUE TITLE
classes and id

### ISSUE THREAD

**Issue by Resolution-1** [mdn/learning-area#211]
add a folder to show the use of classes and id in css selectors

**Comment by Resolution-1** [comment]
I want to work on this

**Comment by chrisdavidmills** [comment]
We already discuss classes and IDs quite extensively on MDN. For example:

* https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started#Adding_a_class (we could do with adding something here about IDs too)
* https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors

And we have examples at https://github.com/mdn/css-examples/tree/master/learn/selectors

What were you thinking of adding?

**Comment by avivmu** [comment]
@Resolution-1 Can we close it?
