### ISSUE TITLE
Favicon is not being loaded in Chrome - any idea why?

### ISSUE THREAD

**Issue by siraj-samsudeen** [mdn/learning-area#224]
As per the tutorial we are supposed to use 
`<link rel="icon" href="favicon.ico" type="image/x-icon">`
But the code in this file uses 
`<link rel="Shortcut Icon" href="favicon.ico" type="image/x-icon" />`
Why is the difference - can you please help me understand?
Even if I change the code to the one used in tutorial, it is not loading.

**Comment by chrisdavidmills** [comment]
I just tried the example in both Chrome and Firefox, and it is working fine for me. What OS are you using?

I think "shortcut icon" is the correct rel to use, so I've changed that in the tutorial so it matches what is in the example file.

**Comment by siraj-samsudeen** [comment]
I am using MacOS.
Kind Regards,
Siraj, Chennai.
+91 97 899 68 576

**Comment by chrisdavidmills** [comment]
> I am using MacOS.

OK, so I am too. In that case, I am not really sure what to suggest here. If you followed the tutorial, it should work ok. Can you should me your code, so I can see if it works on my computer (I'm assuming you've written it by following the tutorial)?

**Comment by siraj-samsudeen** [comment]
Here is the code - filename is "day-2.html"

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Day 2 - June 3, 2020</title>

<link rel="icon" href="favicon.ico" type="image/x-icon" />
</head>
<body>
<p>Japanese example: ご飯が熱い。</p>
</body>
</html>


I stored the favicon.ico in the same folder as this file.

**Comment by chrisdavidmills** [comment]
I just tried your code, and it seems to work fine in Chrome.

**Comment by siraj-samsudeen** [comment]
Ok thanks Chris for the update. Not sure what the issue in my system is. Will check up once my knowledge improves.
