### ISSUE TITLE
Typescript docs and examples

### ISSUE THREAD

**Issue by sai1139** [mdn/learning-area#225]
## Feature Request

Provide Typescript documentation,examples ,show the difference of TS b/w JS for each.

**Comment by chrisdavidmills** [comment]
I feel that providing very much TypeScript documentation would be out of scope for MDN. The TypeScript team have their own docs at https://www.typescriptlang.org/docs/home.html. 

We could probably provide some kind of intro somewhere under https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing, but beyond that, we'd just link to the typescript docs.

**Comment by sai1139** [comment]
@chrisdavidmills thanks for info,

I was suggesting like every user will see MDN for HTML,CSS,JS,some other info.if you add TS docs next to JS ,we can see difference of each example and  how to write TS also. Because most  of information it was there in MDN with standard.

**Comment by chrisdavidmills** [comment]
It sounds like you are suggesting that we add a TS equivalent next to each JS example. Which is a nice idea, but would be way too much work to implement.

I'm closing this for now, but I do appreciate your input, and I will give this some more thought.
