### ISSUE TITLE
300px 

### ISSUE THREAD

**Issue by lfzy** [mdn/learning-area#28]
don't show **300w** of image. 

run as google 

> chrome--版本 57.0.2987.133 (64-bit).

**Comment by chrisdavidmills** [comment]
I don't understand this. Is there a mistake in a particular article you are referring to, or something else?

**Comment by lfzy** [comment]
Thinks!!!!
at the
> learning-area/html/multimedia-and-embedding/responsive-images/responsive.html
I set the viewport width to 300px,but the '300w' of image don't show.
`<img srcset="elva-fairy-320w.jpg 320w,
             elva-fairy-480w.jpg 480w,
             elva-fairy-800w.jpg 800w"
     sizes="(max-width: 320px) 280px,
            (max-width: 480px) 440px,
            800px"
      src="elva-fairy-320w.jpg" alt="Elva dressed as a fairy">`

**Comment by chrisdavidmills** [comment]
Are you using a high res display? In that case your browser might still load up the larger image because a smaller image would look fuzzy on your display.

See this article for explanation:

https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/
