### ISSUE TITLE
Missing meta viewport tag in lesson "Test Your Skills: Fundamental layout comprehension"

### ISSUE THREAD

**Issue by ThalesMarcel** [mdn/learning-area#299]
I am following the lessons of Web Development, and wanted to improve the layout of the exercise proposed in the topic mentioned in the title of this post, making it responsive.
I had a problem using Firefox DevTools to test the page view on mobile devices. As I am still learning, I believed that there was no problem in writing the [HTML and CSS files](https://github.com/mdn/learning-area/tree/master/css/css-layout/fundamental-layout-comprehension) available.
After much research, I realized that the viewport meta tag was missing inside the <head> tag in the [index.html](https://github.com/mdn/learning-area/blob/master/css/css-layout/fundamental-layout-comprehension/index.html) file.
Please correct this, because as we are inspired to go beyond what is proposed in these activities, someone inexperienced like me can get stuck in a silly problem, trusting that the initial file provided is completely correct.

**Comment by chrisdavidmills** [comment]
This is a very good point @ThalesMarcel. I've updated the example files to include the viewport meta tag. Thanks for reporting!

**Comment by RafaelGreen1** [comment]
@chrisdavidmills you might also want to look at this: https://github.com/mdn/css-examples/pull/34

**Comment by ThalesMarcel** [comment]
Thank you very much @RafaelGreen1 and @chrisdavidmills 

For sure, people who use your material to learn Web Development will benefit from it.

**Comment by chrisdavidmills** [comment]
@ThalesMarcel thanks for the kind words!

@RafaelGreen1 sorry for missing that PR earlier; I've merged it, as it looks fine. Thanks!
