### ISSUE TITLE
Alternative of Marquee 

### ISSUE THREAD

**Issue by Manikanta-20** [mdn/learning-area#302]
Provide alternative code for marquee tag through animation css and update in mdn site

I am facing issue to control text speed through animation... because if text length increase speed scrolling automatically increases.

**Comment by chrisdavidmills** [comment]
Hello @Manikanta-20 .  To clarify , you are saying that you are animating some text using the `<marquee>` element, but you want to slow the speed of the text scrolling down?

I would advise you to not use the `<marquee>` tag, as it is a bad practice. Instead, just use something like a paragraph with a wrapper element, styled with CSS, and animated using pure CSS animations. This might help: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations

**Comment by Manikanta-20** [comment]
Hello @chrisdavidmills,I am using below CSS code is working **but I can't able to control the speed if text length increases** ....I have other solution not working.


> CSS
```

.marquee {
    width: 100%
    line-height: 50px;
    background-color: red;
    color: white;
    white-space: nowrap;
    overflow: hidden;
    box-sizing: border-box;
}
.marquee p {
    display: inline-block;
    animation: marquee 15s linear infinite;
}
@keyframes marquee {
    0%   { transform: translateX(100%); }
    100% { transform: translateX(-100%); }
}
```

**Comment by RafaelGreen1** [comment]
just for your information, the marquee tag is obsolete...
see here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee

> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

**Comment by chrisdavidmills** [comment]
@Manikanta-20 to control the speed of the animation, you just need to set an animation time value, and make it larger or small to make the animation happen faster or slower.

I've had a quick play with an example, and something like this should work for you:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>text animation example</title>
    <style>
    .marquee {
      width: 100%;
      height: 50px;
      background-color: red;
      color: white;
      white-space: nowrap;
    }

    .marquee p {
      line-height: 50px;
      font-size: 1.5rem;
      animation: marquee 10s linear infinite;
    }

    @keyframes marquee {
      0%   { transform: translateX(100%); }
      100% { transform: translateX(-100%); }
    }
    </style>
  </head>
  <body>
    <div class="marquee">
      <p>This is my text</p>
    </div>
  </body>
</html>
```

So you set the background color and ther styling on the wrapper `<div>` so that it stays still, and then set the animation on the `<p>` so that it moves inside the wrapper. No `<marquee>` needed. This solution is better practice, and more easily controllable/stylable.

To make it slower or faster. set the '10s' value to a bigger or smaller number.

**Comment by Manikanta-20** [comment]
Thanks @chrisdavidmills, I have added 10s but it is not working. 

Please find below `<p> `  dummy content or below code ...how to control this dynamic content  and time?

**Dummy content** 

`
 popular belief, is not simply random text. It has roots in a piece of classical Latin literature from 87 BC, making it over 2000 years old. Richard , a Latin professor at Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem comes from sections "de et =) by Cicero, written in 87 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of ,                                  The standard chunk of Lorem used since the 1500s is reproduced below for those interested. Sections  from " Malorfewrwkkdum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackharfsadadam.                                  Lorem is simply dummy text of the printing and typesetting industry. Lorem has been the industry&#039;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1938s with the release of Letraset sheets containing Lorem passages, and more recently with desktop publishing software like Aldus zrewewMaker including versions of Lorem .                                  Lorem is simply dummy text of the printing and typesetting industry.      `    

```
or

**code**

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>text animation example</title>
    <style>
    .marquee {
      width: 100%;
      height: 50px;
      background-color: red;
      color: white;
      white-space: nowrap;
    }

    .marquee p {
      line-height: 50px;
      font-size: 1.5rem;
      animation: marquee 10s linear infinite;
    }

    @keyframes marquee {
      0%   { transform: translateX(100%); }
      100% { transform: translateX(-100%); }
    }
    </style>
  </head>
  <body>
    <div class="marquee">
      <p>popular belief, is not simply random text. It has roots in a piece of classical Latin literature from 87 BC, making it over 2000 years old. Richard , a Latin professor at Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem comes from sections "de et =) by Cicero, written in 87 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of ,                                  The standard chunk of Lorem used since the 1500s is reproduced below for those interested. Sections  from " Malorddddum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackharrrrrrm.                                  Lorem is simply dummy text of the printing and typesetting industry. Lorem has been the industry&#039;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1938s with the release of Letraset sheets containing Lorem passages, and more recently with desktop publishing software like Aldus PageddddddMaker including versions of Lorem .                                  Lorem is simply dummy text of the printing and typesetting industry. </p>
    </div>
  </body>
</html>
```

**Comment by chrisdavidmills** [comment]
Hi there @Manikanta-20 !

This is a tricky one! I think the part that threw me was the fact that the marquee text is so much longer than the viewport width, but I've eventually figured out a solution that I think will work for you:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>text animation example</title>
    <style>
    .marquee {
      width: 100%;
      height: 50px;
      background-color: red;
      color: white;
      display: flex;
      align-items: center;
      overflow: hidden;
      font-family: sans-serif;
      position: relative;
    }

    .marquee p {
      position: absolute;
      line-height: 50px;
      font-size: 1.5rem;
      animation: marquee 60s linear infinite;
      white-space: nowrap;
    }

    @keyframes marquee {
      0%   { left : 100% }
      100% { left: -15135px }
    }
    </style>
  </head>
  <body>
    <div class="marquee">

      <p>
        popular belief, is not simply random text. It has roots in a piece of classical Latin literature from 87 BC, making it over 2000 years old. Richard , a Latin professor at Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem comes from sections "de et =) by Cicero, written in 87 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of. The standard chunk of Lorem used since the 1500s is reproduced below for those interested. Sections  from " Malorddddum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackharrrrrrm. Lorem is simply dummy text of the printing and typesetting industry. Lorem has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1938s with the release of Letraset sheets containing Lorem passages, and more recently with desktop publishing software like Aldus PageddddddMaker including versions of Lorem . Lorem is simply dummy text of the printing and typesetting industry.
      </p>

    </div>
  </body>
</html>
```

The key tricky bits were:

1. Figuring out to animate position (`left`) rather than a translate `transform` — because we have a wrapper element around the paragraph, your translate animation was animating it from 100% of the paragraph width, to 0%. 100% of the paragraph width means that it starts miles off to the right. position is relative to its position inside the parent element (the wrapper), so left: 100% puts it just outside the wrapper element, to the right, which is a better place for it to start.
2. Figuring out the length of the paragraph. You've set `white-space: nowrap;` on it, which forces it to be on one single line, but we still need to know how much horizontal position to animate it by. I worked it out in this case by inspecting it in the DevTools inspector, but for a more serious app where you will want it to work for any width of text, you might have to use JavaScript to calculate the width of the paragraph and then fill that in on the CSS before it starts.

I used minus the paragraph width as the final animation value, so that the ends with the paragraph neatly offscreen before it starts animating again.

**Comment by Manikanta-20** [comment]
Hi @chrisdavidmills 

I have tried so many  ways not working as per expectation,Thanks for previous solution
can you provide a good solution of marquee using through animation  and paragraph content can be small/medium/big?

**Comment by Manikanta-20** [comment]
Hi @chrisdavidmills 
Did you find the solution?
