### ISSUE TITLE
Update assets.zip in "structuring-a-page-of-content-start" accessment #2

### ISSUE THREAD

**Issue by Bowi-QC** [mdn/learning-area#307]
Here: https://github.com/mdn/learning-area/tree/master/html/introduction-to-html/structuring-a-page-of-content-start

Someone updated index.html, but forgot to update assets.zip, which is linked [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Structuring_a_page_of_content#Starting_point).

**Comment by chrisdavidmills** [comment]
Thanks for pointing this out. Updated by https://github.com/mdn/learning-area/commit/10575b4117029ed09f3567fd8cce99b505355e0e

**Comment by Bowi-QC** [comment]
No problem. I was about to start a thread on Discourse because the old code gave me an error about the pipe character. 😅
