### ISSUE TITLE
How to hide API key

### ISSUE THREAD

**Issue by bolajiayeni** [mdn/learning-area#308]
I recently started working with APIs and I read it is a bad idea to store your API key in your javascript code, is there any frontend beginner friendly way to hide my api key? (NOTE: I've tried dotenv and dotenv-webpack and none of them seem to work)

**Comment by RafaelGreen1** [comment]
@bolajiayeni one way it to use environment variable, another is to read it from file which is not accessible to the world

**Comment by chrisdavidmills** [comment]
These articles look fairly helpful:

* https://medium.com/better-programming/how-to-hide-your-api-keys-c2b952bc07e6 (React/Rails-specific, but some of the info is general)
* https://www.quora.com/Where-do-I-hide-the-API-key-when-developing-a-frontend-website?share=1

More importantly, I'd probably better add some information to the article to make it clear that this is a necessary step. Do I not mention it at all? ;-)

**Comment by bolajiayeni** [comment]
@chrisdavidmills unfortunately  you do not mention in the article and tbh its been really hard to solve the problem because I use vanilla Javascript with HTML and CSS and most of the solutions online work for frameworks. I've given up for the meanwhile and decided to work on another project. Thanks a lot for your response though

**Comment by bolajiayeni** [comment]
@RafaelGreen1 I tried using enviroment variables but for some reason they don't seem to work with webpack

**Comment by RafaelGreen1** [comment]
@bolajiayeni did you try using the --env option of webpack?

**Comment by chrisdavidmills** [comment]
I filed https://github.com/mdn/sprints/issues/3881 so that we don't forget to deal with this.

**Comment by bolajiayeni** [comment]
Thank you so much, I can't wait to see your solution on how to solve the problem

**Comment by bolajiayeni** [comment]
@RafaelGreen1 that's why I keep having problems, I'm a newbie who only knows frontend and there seems to be no working solutions when using webpack
