### ISSUE TITLE
Layout of can-store not suitable for mobile devices

### ISSUE THREAD

**Issue by fikstoday** [mdn/learning-area#328]
###Can-store is currently not mobile responsive as it retains desktop sized CSS styles.

**Comment by avivmu** [comment]
Hi @fikstoday please add a link to the relevant MDN page

**Comment by fikstoday** [comment]
Oh sorry for the delay. Link ---> https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data
