### ISSUE TITLE
Declaration missing 

### ISSUE THREAD

**Issue by FalcataES** [mdn/learning-area#33]
Is the CSS declaration "flex: 200px;" missing from the CSS code at the Wrapping section of the Flexbox  lecture? It is mentioned on the content and the CSS doesn't seem to work properly without it.

**Comment by chrisdavidmills** [comment]
Hi there,

Do you mean it is mentioned in this section:

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox#Wrapping

?

And that it is missing from the example code? I've checked, and it seems to be in the starter file:

https://github.com/mdn/learning-area/blob/master/css/css-layout/flexbox/flexbox-wrap0.html

If you then add flex-wrap: wrap to the parent section element, it makes the example work properly.

Or am I confused about which bit you mean? ;-)

**Comment by MiHawkStackOverFlow** [comment]
I would like to take this up and push the commit with this change:- 

/* Add your flexbox CSS below here */

      section {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
      }

I added the line flex-wrap: wrap above and checked on my local machine.

Can I make this commit and create a pull request?

**Comment by chrisdavidmills** [comment]
The thing is that this file we are talking about is the starter file for an exercise. In the section I linked above, it tells you to add this line to the example to make it work. Do I need to make that clearer in the text, or maybe add a fixed version of the file for people to look at?

**Comment by FalcataES** [comment]
Hello Chris, 

Yes I meant that I couldn't find it in the example code, but I saw it right now. I couldn't find it the first time because it was in another article declaration. 

If no one else had problems then I think it's better to leave it as it is, 

Thank you for your support! 

S.

**Comment by chrisdavidmills** [comment]
OK, cool, glad you are doing OK now.
