### ISSUE TITLE
Cross-Origin Resouce problem

### ISSUE THREAD

**Issue by NicolaiHygino** [mdn/learning-area#374]
Hi everyone! I'm having problems implementing the Simple Web Audio Example, it's giving this error below. Does anyone know what can it be? 

`The HTMLMediaElement passed to createMediaElementSource has a cross-origin resource, the node will output silence.`

**Comment by bedribulut** [comment]
Most probably you open the index.html file directly on the browser. Instead,  you should set up a local server to local testing. I hope that it helps.
[how to set up a local testing server](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server)
[check this article out 'Reason: CORS request not HTTP'](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp)

**Comment by caugner** [comment]
Closing, as the OP's question was answered in the previous comment. Thanks!
