### ISSUE TITLE
Javascript file using var instead of const

### ISSUE THREAD

**Issue by py-pkulk** [mdn/learning-area#384]
Though not a big deal, the finished .js file under /javascript/apis/video-audio/finsihed/custom-player.js is using "var" for declaring the variables. 

However, the instructions mentioned here https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs are using "const" declaration.

**Comment by hamishwillee** [comment]
Yes, it would be good if that could be fixed. The file is in github - do you think you could update it and re-upload?
