### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by FabsM** [mdn/learning-area#39]
Hi there, 
I'm not sure whether it's the correct section to ask what I'm going to ask in (if not, please let me know and delete this message).
I'm having a look at this HTML file —> [learning-area/html/multimedia-and-embedding/responsive-images/responsive.html](https://github.com/mdn/learning-area/blob/master/html/multimedia-and-embedding/responsive-images/responsive.html)
and I can't get my head around my browser behaviour (I'm using Mozilla Firefox). I'm using the Web Developer tool and  what I'm seeing is that when I change my screen's resolution width to 320px or less what I get is that my browser chooses the 480px image and as soon as I set my screen's resolution width wider than 320px (for example 321px) my browser goes straight for the 800px. The 320px image is not used at all. Why is my browser doing this instead of choosing the right images? 
 
Thanks in advance for your reply

Fabio

**Comment by chrisdavidmills** [comment]
Hi!

One of the issues with srcset is that it provides hints, rather than exact rules. The browser then chooses the best image to display based on its environment. Are you using a device with a hi res display? That is a common cause of the kind of behaviour you are experiencing.

**Comment by FabsM** [comment]
Hi Chris,
first of all thank you for your reply.
Yes, I'm using a notebook with 1920x1080 screen resolution, I thought it was something to do with the different environments and you've confirmed it (I reckon it's impossible to give a real explanation to any behaviour isn't it? )  I will try to set my display resolution to a lower value and see what happenes.

**Comment by chrisdavidmills** [comment]
Cool, glad to hear you are finding it to work OK.
