### ISSUE TITLE
id attrribute missing

### ISSUE THREAD

**Issue by Israel-Beni** [mdn/learning-area#404]
the <form> tag is missing the `id` attribute.
Instead of  `<form novalidate>`  we should have `<form id="form" novalidate>` as the form element is referenced in the script.

**Comment by mikoMK** [comment]
Are you talking about the example on https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation?
We are referencing the form in JS with `const form  = document.getElementsByTagName('form')[0];`. With `getElementsByTagName('form')` we receive an array with all `<form>` elements from which we select the first (and in this case only) one with `[0]`. Therefore there is no need to use an `id`.
