### ISSUE TITLE
Another way to write the calendar (关于日历的另一种写法)

### ISSUE THREAD

**Issue by Kev1n3zz** [mdn/learning-area#469]
按照月份1、3、5、10、12为31天，2月不闰月28天，其余时间30天。这样借助三元运算符就不用在`createCalendar`中传入`days`。
那么这种写法和历程中给出的传days的写法有什么区别呢？ 即使考虑闰月，对于两种写法都是加入判断语句，似乎与不闰月没有不同。

> According to the 1st, 3rd, 5th, 10th and 12th of the month, there are 31 days. February is not a leap month with 28 days, and the rest of the month has 30 days. In this way, with the help of the ternary operator, there is no need to pass in days in createCalendar.
So what is the difference between this way of writing and the way of writing days given in the process? Even if leap months are taken into account, judgment statements are added to both writing methods, which seems to be no different from non-leap months.

```js
var select = document.querySelector('select');
var list = document.querySelector('ul');
var h1 = document.querySelector('h1');

select.onchange = function() {
  var choice = select.value;

  createCalendar(choice);
}

function createCalendar(choice) {
  (choice === 'February')? days = 28
  (choice === 'January'||choice ==='March'||choice ==='May'||choice ==='July'||choice ==='August'||choice ==='October'||choice ==='December')? days=31:days=30;
  list.innerHTML = '';
  h1.textContent = choice;
  for (var i = 1; i <= days; i++) {
    var listItem = document.createElement('li');
    listItem.textContent = i;
    list.appendChild(listItem);
  }
}

createCalendar(choice);
```

**Comment by caugner** [comment]
The issue seems to about this example:

https://github.com/mdn/learning-area/blob/c754e63586d8d897ebee120fe4dcd320e1eefef1/javascript/building-blocks/calendar-finished.html#L51-L80

**Comment by caugner** [comment]
I agree that it would be a better separation of concerns to determine the number of days in the `createCalendar()` function and have that function only take a single parameter ~`choice`~ `monthName`.

**Comment by Vidit151003** [comment]
May I work on this? I am really interested in this issue

**Comment by bsmth** [comment]
> May I work on this? I am really interested in this issue

@Vidit151003 I think you can go ahead and open a pull request to fix this, it doesn't look like anyone else is working on it at the moment :) Thanks a lot!
