### ISSUE TITLE
Update zip file to match the changes made to mdn/content

### ISSUE THREAD

**Issue by deepug9787** [mdn/learning-area#496]
Hi, I just made a [commit ](https://github.com/mdn/content/commit/8ca01014c4ffe482872b4b63be210bf34d224e05)to mdn/content to fix a bug in the source code provided on the [Video and Audio API page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs). On that same page, there is a link to this repo to download the entire code as a [zip file](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs#getting_started). So I just wanted to let you know that the code in the zip file needs to be updated to match the changes made to mdn/content.

Thanks

**Comment by Rumyra** [comment]
For whoever picks this up - check whether keeping the zip file is worth it - if so replace with updated

**Comment by dletorey** [comment]
I'll take this, but don't appear to be able to assign it to myself

**Comment by dletorey** [comment]
I have updated all the content that was wrong.
I left the zip file as it is still and easy route in for new users who are not yet comfortable with git.

[Associated PR](https://github.com/mdn/learning-area/pull/690)

**Comment by bsmth** [comment]
Marking as closed following this PR:

- [x] https://github.com/mdn/learning-area/pull/690

Thanks, all 👍🏻
