### ISSUE TITLE
hummus is mispelled

### ISSUE THREAD

**Issue by phorgan1** [mdn/learning-area#5]
Everywhere hummus is meant, the word humous is used instead. Webster doesn't know that one. Just sayin'. Also on https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals there is an image of this page with no structure that will also need to be fixed since it says _humous_.

**Comment by chrisdavidmills** [comment]
Ha - I saw your changes on the actual MDN article, then went and fixed the code in the repo. Last thing to do is fix the screen shot, which I'll do now!

I can't believe we got away with this for so long. Thanks for bringing it up.

**Comment by phorgan1** [comment]
On 03/29/2017 01:17 AM, Chris Mills
      wrote:
    
    
      Ha - I saw your changes on the actual MDN article, then went
        and fixed the code in the repo. Last thing to do is fix the
        screen shot, which I'll do now!
      I can't believe we got away with this for so long. Thanks for
        bringing it up.
    
    You're welcome:) I usually make changes on software related stuff
    like someone misinterpreting a part of the C++ Standard. It was fun
    to do something about food. When I was going through the page I got
    crazy and made my recipe have alternative tracks for a food
    processor and a mortar and pestle:)
    
    Patrick
    
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mdn/learning-area","title":"mdn/learning-area","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mdn/learning-area"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chrisdavidmills in #5: Ha - I saw your changes on the actual MDN article, then went and fixed the code in the repo. Last thing to do is fix the screen shot, which I'll do now!\r\n\r\nI can't believe we got away with this for so long. Thanks for bringing it up."}],"action":{"name":"View Issue","url":"https://github.com/mdn/learning-area/issues/5#issuecomment-290017488"}}}
