### ISSUE TITLE
The youtube Api example in Third-party APIs article is not working

### ISSUE THREAD

**Issue by kamote-man** [mdn/learning-area#519]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs

### What specific section or headline is this issue about?

YouTube example

### What information was incorrect, unhelpful, or incomplete?

The searched items are not showing after the submit button has clicked.

### What did you expect to see?

To see the Items i input into the searchbar after I click submit button

### Do you have any supporting links, references, or citations?

I'm Sorry, I dont have.

### Do you have anything more you want to share?

I'm Sorry, I dont have it too.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/third_party_apis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/third_party_apis/index.md
* Last commit: https://github.com/mdn/content/commit/3a42980ffc8b3288d52c740692abc7db607057d7
* Document last modified: 2022-07-13T05:22:10.000Z

</details>

**Comment by AMMAR-62** [comment]
Actually this issue need a private API key to be embedded into the code, so what are the work arounds, or how to resolve this??

**Comment by teoli2003** [comment]
Follow these instructions from the article itself.

![Capture d’écran 2022-08-06 à 09 20 14](https://user-images.githubusercontent.com/1466293/183239014-57c02fac-8f06-4a55-9bb8-d66935e5f123.png)

I guess the link to get a key is there: https://developers.google.com/youtube/v3/getting-started

But I'm not sure this is the problem raised by the original poster.

**Comment by AMMAR-62** [comment]
Yes, that is the same reason, the API key needs to be private, and can't be given access to on a public server, you need to embed a api key in the code. And hence the example that is deployed won't work.

**Comment by teoli2003** [comment]
There is nothing more we can do. I'm closing this. Please give us more information on what we should do, if you disagree.
