### ISSUE TITLE
Order should be explained with ordinal numbers

### ISSUE THREAD

**Issue by innthomas** [mdn/learning-area#565]
Rather than use wink, smile, etc, using ordinal numbers like first, second, and third will make explaining easier with CSS order attribute.

**Comment by Rumyra** [comment]
Hi @innthomas thanks for the issue - can you provide a link to where you see the issue - either MDN or in this repo - thanks!

**Comment by innthomas** [comment]
Here is the link : https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox#horizontal_and_vertical_alignment

below is a screenshot 

![image](https://user-images.githubusercontent.com/34725225/202589272-31233449-2403-4c1a-ad01-e1110b1bba76.png)

**Comment by Rumyra** [comment]
Thank you @innthomas 👍

**Comment by dubaiandy** [comment]
不明觉厉

**Comment by bsmth** [comment]
I've closed the linked PR because there is a bit of additional effort involved (screenshots and prose [on the content side](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox#nested_flex_boxes)). If you think that's a mistake, let me know and we can revisit this. Thank you :)
