### ISSUE TITLE
Why file created in tmp folder

### ISSUE THREAD

**Issue by harshsoni-FSD** [mdn/learning-area#590]
I send file from client to server but in between file are copied to tmp folder after completion file not deleted from tmp folder

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code, reporting a problem in a browser or in the specification. Unfortunately, we don't have enough availability to help you.

For a problem in the code, I suggest asking your question on a specialized website like StackOverflow.
For a problem in a browser, you should report it to the browser makers.
For a change in the spec, you should report it in their issue tracker.

I'm closing this issue. If I've misunderstood you and you were reporting a problem in the documentation, feel free to reopen it, while providing more information so we can understand the problem.

Thanks for your interest.
