### ISSUE TITLE
Form example looks ugly.

### ISSUE THREAD

**Issue by ahmedfarouk2** [mdn/learning-area#592]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form#common_html_structures_used_with_forms

### What specific section or headline is this issue about?

https://mdn.github.io/learning-area/html/forms/html-form-structure/payment-form.html

### What information was incorrect, unhelpful, or incomplete?

Well, Just check the live example and you'll know what's wrong. The payment form one.

### What did you expect to see?

A correct example

**Comment by bsmth** [comment]
Hi @ahmedfarouk2 - I've transferred this one over to the learning-are repo. The source of the example you're talking about can be found here: https://github.com/mdn/learning-area/blob/main/html/forms/html-form-structure/payment-form.html

**Comment by ahmedfarouk2** [comment]
Thank you for noting bsmth!

**Comment by CalinObo** [comment]
Hey @bsmth , I noticed the issue he was talking about, I did a pull-request, I`m new to github so I do not know if I did it right, the thing is that margin-right should be used instead of margin-left. It looks out of place with margin-left.

**Comment by bsmth** [comment]
> Hey @bsmth , I noticed the issue he was talking about, I did a pull-request, I`m new to github so I do not know if I did it right, the thing is that margin-right should be used instead of margin-left. It looks out of place with margin-left.

I spotted you have a branch, but you need to create a pull request. You can give it a shot here: https://github.com/mdn/learning-area/compare/main...CalinObo:learning-area:patch-1

Although this looks like a good addition, I'm not sure it fixes the issue @ahmedfarouk2 is talking about. Ahmed, did you want to have the form use a colorful stylesheet with better design in general?

**Comment by ahmedfarouk2** [comment]
@bsmth No Brian, as our friend commented there's a problem in the margins, It's not about beauty it's not semantically correct. Thanks!

**Comment by CalinObo** [comment]
> > Hey @bsmth , I noticed the issue he was talking about, I did a pull-request, I`m new to github so I do not know if I did it right, the thing is that margin-right should be used instead of margin-left. It looks out of place with margin-left.
> 
> I spotted you have a branch, but you need to create a pull request. You can give it a shot here: [main...CalinObo:learning-area:patch-1](https://github.com/mdn/learning-area/compare/main...CalinObo:learning-area:patch-1)
> 
> Although this looks like a good addition, I'm not sure it fixes the issue @ahmedfarouk2 is talking about. Ahmed, did you want to have the form use a colorful stylesheet with better design in general?

I created a pull request, do you have any usefull resources as to How to use github? I`m new to this thing and I want to try and help. Let me know if what I did is usefull. Thank you very much @bsmth

**Comment by bsmth** [comment]
Fixed by @CalinObo in https://github.com/mdn/learning-area/pull/594

Well done 🙌🏻
