### ISSUE TITLE
oojs.html example shows HTML0204 lint warning 

### ISSUE THREAD

**Issue by TheCodePilot** [mdn/learning-area#595]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics

### What specific section or headline is this issue about?

javascript/oojs/introduction/oojs.html

### What information was incorrect, unhelpful, or incomplete?

<body>
    <p>This ...</p>

</body>

<script>

</script>
</html>

### What did you expect to see?

    <body>
        <p> ...</p>
        <script>

        </script>
    </body>

</html>

### Do you have any supporting links, references, or citations?

Ich arbeite mit Visual Studio. Wenn ich das Skript:
javascript/oojs/introduction/oojs.html
entsprechend kopiere:
Bekomme ich diesen Hinweis siehe Bild.

Ich bin sehr zufrieden mit Eurer Arbeit und alles andere war auch nie ein
![Fehler](https://user-images.githubusercontent.com/116466353/220936174-ffeca805-86bd-497c-9ffc-ad071a81b19e.png)
 Problem wenn ich Code von Euch zum Üben nutzte. 

### Do you have anything more you want to share?

Ich bitte um Antwort. 
Mit freundlichen Grüßen:

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/basics/index.md
* Last commit: https://github.com/mdn/content/commit/8317f50d476fde0d11178db467b25a859670e927
* Document last modified: 2023-02-21T18:33:04.000Z

</details>

**Comment by bsmth** [comment]
Hi @TheCodePilot - thanks for raising the issue. I've transferred this over to the learning area repository.

You're right that the `<script>` element should be inside the `<body>`, or in the `<head>`:

```html
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Object-oriented JavaScript example</title>

    <script></script>
  </head>

  <body>
    <p>
      This example requires you to enter commands in your browser's JavaScript
      console (see
      <a
        href="https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools"
        >What are browser developer tools</a
      >
      for more information).
    </p>
  </body>
</html>

```

Would you like to [open a pull request to fix it](https://github.com/mdn/learning-area/blob/main/javascript/oojs/introduction/oojs.html)? You can get started here on GitHub directly if you like:

![Screenshot 2023-02-24 at 10 31 15 AM](https://user-images.githubusercontent.com/43580235/221143715-84d97980-d136-4035-8354-2f6ee9f50850.png)

**Comment by TheCodePilot** [comment]
I am a little nervous,
because 2 weeks ago. i knewn nothing about HTML, CSS or Java Script. I am
C++ Developer normally.

If you mean I can, then I will try to fix it on Github.

greetings

Am Fr., 24. Feb. 2023 um 10:35 Uhr schrieb Brian Thomas Smith <
***@***.***>:

**Comment by bsmth** [comment]
Well done on your contribution and welcome! 🎉

I'm going to close the issue as fixed in https://github.com/mdn/learning-area/pull/
