### ISSUE TITLE
Is this a typo, or am i misunderstanding it?

### ISSUE THREAD

**Issue by pbbob1** [mdn/learning-area#61]
I am learning javascript, and here: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Functions#Anonymous_functions

If you read down a little bit, it says "This effectively gives the variable a name; you can also assign the function to be the value of multiple variables, for example:" shouldn't it instead say "This effectively gives the _function_ a name; you can also assign the function to be the value of multiple variables, for example:"

**Comment by chrisdavidmills** [comment]
Yup, you are right - this is a typo. I've update it now - thanks for reporting!
