### ISSUE TITLE
[revise] fix payment form code snippet

### ISSUE THREAD

**Issue by CBID2** [mdn/learning-area#629]
Originally from @hamishwillee in [#26790](https://github.com/mdn/content/issues/26790)
The action is to add `required="true"` to any field that should be required, and make sure there are corresponding aria markup for those same case. The associated example should be updated in tandem, and merged at the same time: https://github.com/mdn/learning-area/blob/main/html/forms/html-form-structure/payment-form.html

**Comment by hamishwillee** [comment]
Closing. This issue is not needed for tracking. See https://github.com/mdn/content/issues/26790
