### ISSUE TITLE
Shared from Bing: https://www.rndframe.com/server/privacy.html?site=onlineloannetwork.com

### ISSUE THREAD

**Issue by Montana63** [mdn/learning-area#631]
https://www.rndframe.com/server/privacy.html?site=onlineloannetwork.com

**Comment by Montana63** [comment]
Thanks for the advice and the great idea for me to come with the company

**Comment by hamishwillee** [comment]
Please stop using MDN repos as a sandbox. It is a waste of many other developer's time.
