### ISSUE TITLE
Test your skills: Advanced HTML text — Task 2, paragraph 2: Copy discrepancy

### ISSUE THREAD

**Issue by fredhartley** [mdn/learning-area#641]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Advanced_HTML_text

### What specific section or headline is this issue about?

Task 2

### What information was incorrect, unhelpful, or incomplete?

There is a copy discrepancy between the finished examples and the live code in paragraph 2, task 2. 

Finished example copy: "HTML, Hypertext Markup Language is by default accessible, if used correctly."
Default live code: "By default, HTML is accessible, if used correctly."

### What did you expect to see?

The same copy between the finished example copy and the default life code. I.e. both "HTML, Hypertext Markup Language is by default accessible, if used correctly."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/test_your_skills_colon__advanced_html_text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Advanced_HTML_text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/test_your_skills_colon__advanced_html_text/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by letsbecometechie** [comment]
Hi @mikoMK / @bsmth, is this still open?
If yes can you please assign it to me? Happy to take it up

**Comment by vanshdhar999** [comment]
Is this issue still open?

**Comment by bsmth** [comment]
This is now fixed by @letsbecometechie in https://github.com/mdn/learning-area/pull/654

Thanks, all!
