### ISSUE TITLE
Inconsistency with the courses

### ISSUE THREAD

**Issue by joan38** [mdn/learning-area#67]
Hi,

This commit https://github.com/mdn/learning-area/commit/fb60ed9da24544cf481ed5d5b055dd682afb440e#diff-0eab77173ff17cb7ef2c478598ec7739L9 removed all the HTML and made this course confusing:
https://developer.mozilla.org/fr/docs/Learn/JavaScript/Objects/Basics

@chrisdavidmills should we revert your commit?

Cheers

**Comment by chrisdavidmills** [comment]
No. I'm afraid the French translation needs updating so it matches the English one. I ended up removing the HTML from those examples and asking people to just open up the browser developer tools and enter the commands into the JavaScript console.

I did this because the HTML form was confusing people even more — they were entering commands into it and then not seeing any result because the results were appearing in the JS Console!

I have updated the examples again to hopefully make it a bit more obvious what readers need to do.

**Comment by joan38** [comment]
I see. I will have a look about the French version, thanks.

**Comment by typhoon93** [comment]
What's going on here?

**Comment by joan38** [comment]
Hi @typhoon93 I will not have time to do the change.
If anyone is happy to do it feel free.

**Comment by debasree88** [comment]
i will be happy to do it. Pls assign this task to me @joan38

**Comment by joan38** [comment]
@debasree88 feel free to submit a PR.

**Comment by debasree88** [comment]
Okay.thank you. @joan38

**Comment by debasree88** [comment]
so what i understood i need to add the suitable html for this " javascript/oojs/introduction/oojs.html" file for the live view of code as before?

**Comment by joan38** [comment]
@debasree88 no, the French version needs to be changed to match the new English.
Do you speak French? If not it's going to be hard for you :)

**Comment by debasree88** [comment]
So I just need to work on the French version to match the new English version? And for that I can easily learn the basics of french and rest i will do with the help of internet☺️

**Comment by debasree88** [comment]
Sorry sir... Actually this is my 1st try towards open source contributions
and I m still having doubt relating to the issue. If you clear my doubt I
will be able to submit a proper PR. And my doubt is what is the
inconsistency between the eng and french versions...I apparently don't see
any when I open both in browser...

**Comment by joan38** [comment]
Actually it's not a PR that needs to be done. It's a change on the course.

**Comment by debasree88** [comment]
Okay. I m willing to do. Please elaborate the matter sir.

**Comment by SerdarAtalay** [comment]
Is this issue still exists?

**Comment by chrisdavidmills** [comment]
Closing this, as noone seems to have the time to fix it.
