### ISSUE TITLE
Standardize lang attribute usage in HTML tutorial on MDN to 'en-US' or 'en-us'

### ISSUE THREAD

**Issue by kuthathwe** [mdn/learning-area#672]
While studying the HTML tutorial on MDN, I observed inconsistencies in the use of the lang attribute within HTML files. I have been seeing the following variations: ```<html lang="en">```, ```<html lang="en-us">```, and ```<html lang="en-US">```. As a prominent learning platform, it would be beneficial to standardize the usage as either **"en-US"** or **"en-us"**

**Comment by luv2027** [comment]
Heya @caugner, can i work on this issue ?

**Comment by caugner** [comment]
@luv2027 Sure, I have assigned you now.

**Comment by luv2027** [comment]
@caugner can you please review my pr. it would be really helpful
