### ISSUE TITLE
TypeError: gulp.task is not a function

### ISSUE THREAD

**Issue by TeckyBecky17** [mdn/learning-area#82]
I am following https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Automated_testing#Setting_up_Node_and_npm step by step. I have overcome most problems, seemingly down to the way NPM has been installed on my W10 machine, but I am stuck on the error "TypeError: gulp.task is not a function". I can't tell if this is because i have made a mistake somewhere or if i am calling an out of date / deprecated function on a newer version of npm. Is it possible to get a copy of a working sample for the full gulpfil.js please? Mine is attached.
[gulpfile.js.txt](https://github.com/mdn/learning-area/files/2210245/gulpfile.js.txt)

**Comment by chrisdavidmills** [comment]
Hi there,

I tested it all, and also updated a complete version of `gulpfile.js` to our repo so you can see what it is supposed to look like: https://github.com/mdn/learning-area/blob/master/tools-testing/cross-browser-testing/automation/gulpfile.js

One thing I did find is that gulp-babel now requires babel-core to be installed as a separate dependency (see https://github.com/babel/gulp-babel/issues/124), so this additional command needs to be run inside your package directory:

```
npm install --save-dev babel-core
```

I've updated the docs to include this command.

Let me know if this helped. Thanks!
