### ISSUE TITLE
Embedded consoles on Javascript learning resources are out of work (chrome, safari)

### ISSUE THREAD

**Issue by B3nnyL** [mdn/learning-area#87]
As title.
Reproduce link: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Useful_string_methods

**Comment by chrisdavidmills** [comment]
What problems are you finding with these? I've just done some testing and they seem to work OK in Chrome/Safari.

**Comment by chrisdavidmills** [comment]
Hrm, const and let don't seem to work, but var still does

**Comment by B3nnyL** [comment]
@chrisdavidmills  It's not about functionalities; the consoles don't react according to my inputs. I created two gif screenshots for you.  In the gifs, I could highlight the symbol; but, if I typed, the interface never updated and froze there.

![embeded](http://ibucket233-1.s3-ap-southeast-2.amazonaws.com/embeded-chrome.gif)
![page](http://ibucket233-1.s3-ap-southeast-2.amazonaws.com/page-chrome.gif)

The same thing happens with Safari. Any thoughts?

**Comment by chrisdavidmills** [comment]
I've tried it, and yes, if you highlight the symbol it doesn't work.

Instead, you have to click next to the symbol and then type. It works then, and this is how terminals tend to react. You can also tab into the box and it will put the cursor in the right place and work.

**Comment by B3nnyL** [comment]
It works! Thanks for the instruction.
If the terminal could come with a blinking cursor, it would be nice.

**Comment by chrisdavidmills** [comment]
Yeah, it would be nice. Unfortunately the only way for me to have a blinking cursor with no user interaction is to use JavaScript to focus the terminal on page load, which causes another problem — the article immediately jumps straight to that point, which is confusing and odd.

I thought this was the lesser of two evils ;-)

**Comment by B3nnyL** [comment]
Yeah, you're right. It comes with other side-effects.
What about adding a static cursor behind the input symbol?  I made a mockup and attached below

![a quick mockup](http://ibucket233-1.s3-ap-southeast-2.amazonaws.com/mdn-terminal-mockup.png)
