### ISSUE TITLE
http://html5shiv.googlecode.com/svn/trunk/html5.js 404

### ISSUE THREAD

**Issue by xuchunyang** [mdn/learning-area#97]
https://github.com/mdn/learning-area/blob/5bc75c7f4f6221db6cf7b389da17663d83372e6c/html/introduction-to-html/document_and_website_structure/index.html#L12

mentions the link http://html5shiv.googlecode.com/svn/trunk/html5.js, but it's 404.

**Comment by chrisdavidmills** [comment]
Good point! I have updated them to an HTML5Shiv location that still exists.

https://github.com/mdn/learning-area/commit/776deace7ee2aaef264e50989594c3cd892eb49c
